version: '3'

services:
  app:
    container_name: tate-app
    ports:
      - "8000:80"
    build: ./Docker/App
    volumes:
      - ./html:/var/www/html
    working_dir: /var/www/html/backend

  db:
    image: mysql:5.7
    container_name: tate-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./Docker/DB/volume:/var/lib/mysql
      - ./Docker/DB/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 13306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 3000:80