@name = hidari-tate

# ローカル
@baseUrl = http://localhost:8000/api
# ステージング
# @baseUrl = http://163.44.254.176:80/api
# プロダクト
# @baseUrl = http://163.44.253.210:80/api

@token = Bearer Z5vtDT9gffd9G2DF99Bt8TlP2wAXinb8ngyZPfgiHE1IhhoKqqtVTydEu5yqDNsG

// 会員作成
###################################################
POST {{baseUrl}}/app/create_member HTTP/1.1
Content-Type: application/json

{
    "member_name": "hiroto",
    "login_id": "hiroto",
    "password": "hiroto",
    "user_login_id": "tate6416",
    "user_name": "tatemichi"
}

// ログイン
###################################################
POST {{ baseUrl }}/app/login HTTP/1.1
Content-Type: application/json

{
    "login_id": "tate6416",
    "password": "tatemiti1"
}

// ログアウト
###################################################
GET {{ baseUrl }}/app/logout HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

// マイページトップ会員情報取得
###################################################
GET {{ baseUrl }}/app/get_top_profile HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json


// スコアルーム作成
###################################################
POST {{ baseUrl }}/app/create_score_room HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

{
    "default_score": 100,
    "room_name": "test01",
    "room_password": "123456",
    "host_color": 1,
    "guest1_color": "2",
    "guest2_color": "3",
    "guest3_color": "",
    "guest4_color": ""
}

// スコアルーム作成画面項目
###################################################
GET {{ baseUrl }}/app/menu/create_score_room HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

// スコアルーム一覧
###################################################
GET {{ baseUrl }}/app/list_score_room HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

// スコアルーム情報取得
###################################################
GET {{ baseUrl }}/app/get_score_room?score_room_id=1 HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

// スコアルーム参加
###################################################
POST {{ baseUrl }}/app/join_score_room HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

{
    "score_room_id": 1,
    "member_no": 1,
    "room_password": "123456"
}

// スコアルーム詳細取得
###################################################
POST {{ baseUrl }}/app/get_detail_score_room HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

{
    "score_room_id": 1,
    "member_no": 0
}

// スコアルーム・スコア更新
###################################################
POST {{ baseUrl }}/app/update_score_room HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

{
    "score_room_id": 1,
    "scores": [-500, 500, 0, 0, 0]
}

// スコアルームリセット
###################################################
GET {{ baseUrl }}/app/reset_score_room HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

// スコアルームログアウト
###################################################
GET {{ baseUrl }}/app/logout_score_room?score_room_id=1 HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

// スコアルームゲストログアウト
###################################################
POST {{ baseUrl }}/app/logout_guest_score_room HTTP/1.1
Authorization: {{ token }}
Content-Type: application/json

{
    "score_room_id": 1,
    "member_no": 1
}

// 動作確認
###################################################
GET {{ baseUrl }}/insider/ini HTTP/1.1
Content-Type: application/json